development:
  adapter:    postgresql
  encoding:   unicode
  database:   flight_booker_development
  host:       localhost
  pool:       5
  username:   salomanuel
  password:   4852


test:
  adapter:    postgresql
  encoding:   unicode
  database:   flight_booker_test
  pool:       5
  username:   salomanuel
  password:   4852
