development:
  adapter:    postgresql
  encoding:   unicode
  database:   flight_booker_development
  host:       localhost
  pool:       5
  username:   flight-user
  password:   password


test:
  adapter:    postgresql
  encoding:   unicode
  database:   flight_booker_test
  pool:       5
  username:   flight-user
  password:   password
